CREATE TABLE public.students (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	name varchar(255) NOT NULL,
	student_card int8 NOT NULL,
	CONSTRAINT students_pkey PRIMARY KEY (id)
);
CREATE INDEX ix_students_student_card ON public.students USING btree (student_card);

CREATE TABLE public.courses (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	booked_seats int4 NOT NULL,
	course_name varchar(255) NOT NULL,
	end_time timestamptz NOT NULL,
	start_time timestamptz NOT NULL,
	total_seats int4 NOT NULL,
	CONSTRAINT courses_pkey PRIMARY KEY (id)
);

CREATE TABLE public.registrations (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	course_id int8 NOT NULL,
	student_id int8 NOT NULL,
	CONSTRAINT registrations_pkey PRIMARY KEY (id),
	CONSTRAINT students_fk FOREIGN KEY (student_id) REFERENCES public.students(id),
	CONSTRAINT courses_fk FOREIGN KEY (course_id) REFERENCES public.courses(id)
);
CREATE INDEX fk_registration_students_student_id ON public.registrations USING btree (student_id);
CREATE INDEX fk_registration_courses_course_id ON public.registrations USING btree (course_id);