CREATE TABLE public.students (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	name varchar(255) NOT NULL,
	student_id int4 NOT NULL,
	CONSTRAINT students_pkey PRIMARY KEY (id)
);
CREATE INDEX idx5mbus2m1tm2acucrp6t627jmx ON public.students USING btree (student_id);

CREATE TABLE public.courses (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	booked_seats int4 NULL,
	course_name varchar(255) NOT NULL,
	end_time timestamptz NULL,
	start_time timestamptz NULL,
	total_seats int4 NULL,
	CONSTRAINT courses_pkey PRIMARY KEY (id)
);

CREATE TABLE public.registrations (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	course_id int8 NULL,
	student_id int8 NULL,
	CONSTRAINT registrations_pkey PRIMARY KEY (id),
	CONSTRAINT fkcmo9lk1tap4hpbawuxhb8qf94 FOREIGN KEY (student_id) REFERENCES public.students(id),
	CONSTRAINT fksfbbeggcdx583ihht1yngeam6 FOREIGN KEY (course_id) REFERENCES public.courses(id)
);